services:
  monaserver:
    build: .
    container_name: monaserver
    ports:
      - '4000:4000'
    volumes:
      - '.:/usr/src/myapp'
    working_dir: '/usr/src/myapp'
    networks:
      - mona
    depends_on:
      - postgres
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - './pgdata:/var/lib/postgresql/data'
    networks:
      - mona
networks:
  mona:
    driver: bridge
